### ISSUE TITLE
Error converting bitecode to dex

### ISSUE THREAD

**Issue by Benetzz** [Shmarkus/cordova-plugin-nuance-speechkit#1]
Hi, I have an error after installing this plugin. It happen only running on emulator or generating apk. 

```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/nuance/nmsp/client/sdk/oem/AudioSystemOEM;

Error:Execution failed for task ':transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
```

Any ideas about what's happeing here? Using gradle:2.2.3 on API 23.

Thank!

**Comment by Shmarkus** [comment]
Hi,
I'll try to reproduce.

**Comment by Shmarkus** [comment]
Try to clean before build; update Gradle and try then. If this doesn't work, see if there are any package name problems. This issue seems unrelated to speechkit plugin.
