### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by sebattenti** [Shmarkus/cordova-plugin-nuance-speechkit#2]
I tried a lot of things to make it work but it's not working
Can someone send a demo example?
I'm currently working with Ionic 3

Thanks

**Comment by Shmarkus** [comment]
Hi, the example is [here](https://github.com/Shmarkus/cordova-plugin-nuance-speechkit-sample)

To use the plugin you need to (until I get my [pull request](https://github.com/ionic-team/ionic-native/pull/2345) approved) manually add this folder to node_modules/@ionic-native folder: https://drive.google.com/file/d/1XedFOrK3ORHkRAF0Opxvxo3lTQ7AOLu9/view?usp=sharing (other alternative would be to use my [ionic-native](https://github.com/Shmarkus/ionic-native))
 
With this in place, you should get the example working. (please add your own API_KEY and URL to package.json and config.xml)

**Comment by Shmarkus** [comment]
@sebattenti let me know how you progress, if you managed to get it working, I'll close the issue

**Comment by sebattenti** [comment]
Hi Markus,

I could make it work, thanks for the help!

The ASR is not implemented yet? This could be great!


Thanks,

Sebastian Bekerman | Mobile Team Leader
[Logo-Attenti]
2 Habarzel St. | Tel Aviv 69710 | Israel
Office: +972 3 7671700 ext. 6432 | Mobile: +972 54 3281021 | Fax: +972 3 7671701
sbekerman@attentigroup.com<mailto:sbekerman@attentigroup.com>

**Comment by Shmarkus** [comment]
@sebattenti the ASR should work for Android. If you are proficient in Objective-C, you could make a pull request to merge IOS ASR code.
